# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements/development.txt
before_script:
  - prospector
script: pytest --cov
