# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements/development.txt
jobs:
  include:
    - script: prospector
      env:
        - JOB_LABEL='prospector linting'
    - script: pytest --cov
      env:
        - JOB_LABEL='pytest and coverage'
