# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\window\asset.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssetDialog(object):
    def setupUi(self, AssetDialog):
        AssetDialog.setObjectName("AssetDialog")
        AssetDialog.resize(350, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssetDialog.sizePolicy().hasHeightForWidth())
        AssetDialog.setSizePolicy(sizePolicy)
        AssetDialog.setMinimumSize(QtCore.QSize(350, 600))
        AssetDialog.setMaximumSize(QtCore.QSize(500, 750))
        AssetDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        AssetDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssetDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.categoryGroup = QtWidgets.QGroupBox(AssetDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.categoryGroup.setFont(font)
        self.categoryGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.categoryGroup.setFlat(False)
        self.categoryGroup.setCheckable(False)
        self.categoryGroup.setObjectName("categoryGroup")
        self.layoutVtlCat = QtWidgets.QVBoxLayout(self.categoryGroup)
        self.layoutVtlCat.setObjectName("layoutVtlCat")
        self.categoryComboBox = QtWidgets.QComboBox(self.categoryGroup)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.layoutVtlCat.addWidget(self.categoryComboBox)
        self.variantGroupBox = QtWidgets.QGroupBox(self.categoryGroup)
        self.variantGroupBox.setCheckable(True)
        self.variantGroupBox.setChecked(False)
        self.variantGroupBox.setObjectName("variantGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.variantGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.variantRadioAlphabet = QtWidgets.QRadioButton(self.variantGroupBox)
        self.variantRadioAlphabet.setChecked(True)
        self.variantRadioAlphabet.setObjectName("variantRadioAlphabet")
        self.horizontalLayout.addWidget(self.variantRadioAlphabet)
        self.variantRadioNumber = QtWidgets.QRadioButton(self.variantGroupBox)
        self.variantRadioNumber.setChecked(False)
        self.variantRadioNumber.setObjectName("variantRadioNumber")
        self.horizontalLayout.addWidget(self.variantRadioNumber)
        self.layoutVtlCat.addWidget(self.variantGroupBox)
        self.verticalLayout.addWidget(self.categoryGroup)
        self.detailsGroup = QtWidgets.QGroupBox(AssetDialog)
        self.detailsGroup.setEnabled(True)
        self.detailsGroup.setObjectName("detailsGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.detailsGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shortNameLabel = QtWidgets.QLabel(self.detailsGroup)
        self.shortNameLabel.setObjectName("shortNameLabel")
        self.verticalLayout_2.addWidget(self.shortNameLabel)
        self.shortNameLineEdit = QtWidgets.QLineEdit(self.detailsGroup)
        self.shortNameLineEdit.setMaxLength(3)
        self.shortNameLineEdit.setObjectName("shortNameLineEdit")
        self.verticalLayout_2.addWidget(self.shortNameLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.detailsGroup)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_2.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.detailsGroup)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout_2.addWidget(self.nameLineEdit)
        self.descLabel = QtWidgets.QLabel(self.detailsGroup)
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout_2.addWidget(self.descLabel)
        self.descTextEdit = QtWidgets.QPlainTextEdit(self.detailsGroup)
        self.descTextEdit.setObjectName("descTextEdit")
        self.verticalLayout_2.addWidget(self.descTextEdit)
        self.verticalLayout.addWidget(self.detailsGroup)
        self.previewGroup = QtWidgets.QGroupBox(AssetDialog)
        self.previewGroup.setFlat(False)
        self.previewGroup.setCheckable(True)
        self.previewGroup.setChecked(False)
        self.previewGroup.setObjectName("previewGroup")
        self.layoutVtlPreview = QtWidgets.QVBoxLayout(self.previewGroup)
        self.layoutVtlPreview.setObjectName("layoutVtlPreview")
        self.previewText = QtWidgets.QPlainTextEdit(self.previewGroup)
        self.previewText.setReadOnly(True)
        self.previewText.setObjectName("previewText")
        self.layoutVtlPreview.addWidget(self.previewText)
        self.verticalLayout.addWidget(self.previewGroup)
        self.layoutCreateCancel = QtWidgets.QHBoxLayout()
        self.layoutCreateCancel.setObjectName("layoutCreateCancel")
        self.btnCreate = QtWidgets.QPushButton(AssetDialog)
        self.btnCreate.setObjectName("btnCreate")
        self.layoutCreateCancel.addWidget(self.btnCreate)
        self.btnCancel = QtWidgets.QPushButton(AssetDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.layoutCreateCancel.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.layoutCreateCancel)

        self.retranslateUi(AssetDialog)
        QtCore.QMetaObject.connectSlotsByName(AssetDialog)

    def retranslateUi(self, AssetDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetDialog.setWindowTitle(_translate("AssetDialog", "Create New Asset"))
        self.categoryGroup.setTitle(_translate("AssetDialog", "Category"))
        self.variantGroupBox.setTitle(_translate("AssetDialog", "Variant"))
        self.variantRadioAlphabet.setText(_translate("AssetDialog", "Alphabet"))
        self.variantRadioNumber.setText(_translate("AssetDialog", "Number"))
        self.detailsGroup.setTitle(_translate("AssetDialog", "Details"))
        self.shortNameLabel.setText(_translate("AssetDialog", "Shortname"))
        self.shortNameLineEdit.setToolTip(_translate("AssetDialog", "Alphanumeric only"))
        self.nameLabel.setText(_translate("AssetDialog", "Full Name"))
        self.descLabel.setText(_translate("AssetDialog", "Description"))
        self.descTextEdit.setPlaceholderText(_translate("AssetDialog", "Asset\'s description goes here"))
        self.previewGroup.setTitle(_translate("AssetDialog", "Preview"))
        self.btnCreate.setText(_translate("AssetDialog", "Create"))
        self.btnCancel.setText(_translate("AssetDialog", "Cancel"))
