# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\window\asset_item.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssetItemDialog(object):
    def setupUi(self, AssetItemDialog):
        AssetItemDialog.setObjectName("AssetItemDialog")
        AssetItemDialog.resize(310, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssetItemDialog.sizePolicy().hasHeightForWidth())
        AssetItemDialog.setSizePolicy(sizePolicy)
        AssetItemDialog.setMinimumSize(QtCore.QSize(310, 360))
        AssetItemDialog.setMaximumSize(QtCore.QSize(310, 360))
        AssetItemDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        AssetItemDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssetItemDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.assetLayout = QtWidgets.QHBoxLayout()
        self.assetLayout.setObjectName("assetLayout")
        self.assetLabel = QtWidgets.QLabel(AssetItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetLabel.sizePolicy().hasHeightForWidth())
        self.assetLabel.setSizePolicy(sizePolicy)
        self.assetLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.assetLabel.setObjectName("assetLabel")
        self.assetLayout.addWidget(self.assetLabel)
        self.assetComboBox = QtWidgets.QComboBox(AssetItemDialog)
        self.assetComboBox.setObjectName("assetComboBox")
        self.assetLayout.addWidget(self.assetComboBox)
        self.verticalLayout.addLayout(self.assetLayout)
        self.formatLayout = QtWidgets.QHBoxLayout()
        self.formatLayout.setObjectName("formatLayout")
        self.formatLabel = QtWidgets.QLabel(AssetItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatLabel.sizePolicy().hasHeightForWidth())
        self.formatLabel.setSizePolicy(sizePolicy)
        self.formatLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.formatLabel.setObjectName("formatLabel")
        self.formatLayout.addWidget(self.formatLabel)
        self.formatComboBox = QtWidgets.QComboBox(AssetItemDialog)
        self.formatComboBox.setObjectName("formatComboBox")
        self.formatLayout.addWidget(self.formatComboBox)
        self.verticalLayout.addLayout(self.formatLayout)
        self.checkboxCopyIncrement = QtWidgets.QCheckBox(AssetItemDialog)
        self.checkboxCopyIncrement.setEnabled(False)
        self.checkboxCopyIncrement.setObjectName("checkboxCopyIncrement")
        self.verticalLayout.addWidget(self.checkboxCopyIncrement)
        self.shortNameVersionLayout = QtWidgets.QHBoxLayout()
        self.shortNameVersionLayout.setObjectName("shortNameVersionLayout")
        self.shortNameLayout = QtWidgets.QHBoxLayout()
        self.shortNameLayout.setObjectName("shortNameLayout")
        self.shortNameLabel = QtWidgets.QLabel(AssetItemDialog)
        self.shortNameLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.shortNameLabel.setObjectName("shortNameLabel")
        self.shortNameLayout.addWidget(self.shortNameLabel)
        self.shortNameLineEdit = QtWidgets.QLineEdit(AssetItemDialog)
        self.shortNameLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortNameLineEdit.sizePolicy().hasHeightForWidth())
        self.shortNameLineEdit.setSizePolicy(sizePolicy)
        self.shortNameLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.shortNameLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.shortNameLineEdit.setMaxLength(3)
        self.shortNameLineEdit.setObjectName("shortNameLineEdit")
        self.shortNameLayout.addWidget(self.shortNameLineEdit)
        self.shortNameVersionLayout.addLayout(self.shortNameLayout)
        self.versionLayout = QtWidgets.QHBoxLayout()
        self.versionLayout.setObjectName("versionLayout")
        self.versionLabel = QtWidgets.QLabel(AssetItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLabel.sizePolicy().hasHeightForWidth())
        self.versionLabel.setSizePolicy(sizePolicy)
        self.versionLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.versionLabel.setObjectName("versionLabel")
        self.versionLayout.addWidget(self.versionLabel)
        self.versionSpinBox = QtWidgets.QSpinBox(AssetItemDialog)
        self.versionSpinBox.setEnabled(False)
        self.versionSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.versionSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.versionSpinBox.setProperty("value", 1)
        self.versionSpinBox.setObjectName("versionSpinBox")
        self.versionLayout.addWidget(self.versionSpinBox)
        self.shortNameVersionLayout.addLayout(self.versionLayout)
        self.verticalLayout.addLayout(self.shortNameVersionLayout)
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setObjectName("nameLayout")
        self.nameLabel = QtWidgets.QLabel(AssetItemDialog)
        self.nameLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.nameLabel.setObjectName("nameLabel")
        self.nameLayout.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(AssetItemDialog)
        self.nameLineEdit.setEnabled(False)
        self.nameLineEdit.setPlaceholderText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLayout.addWidget(self.nameLineEdit)
        self.verticalLayout.addLayout(self.nameLayout)
        self.descLayout = QtWidgets.QHBoxLayout()
        self.descLayout.setObjectName("descLayout")
        self.descLabel = QtWidgets.QLabel(AssetItemDialog)
        self.descLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descLabel.sizePolicy().hasHeightForWidth())
        self.descLabel.setSizePolicy(sizePolicy)
        self.descLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.descLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descLabel.setObjectName("descLabel")
        self.descLayout.addWidget(self.descLabel)
        self.descTextEdit = QtWidgets.QPlainTextEdit(AssetItemDialog)
        self.descTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descTextEdit.sizePolicy().hasHeightForWidth())
        self.descTextEdit.setSizePolicy(sizePolicy)
        self.descTextEdit.setMaximumSize(QtCore.QSize(16777215, 125))
        self.descTextEdit.setObjectName("descTextEdit")
        self.descLayout.addWidget(self.descTextEdit)
        self.verticalLayout.addLayout(self.descLayout)
        self.infoLabel = QtWidgets.QLabel(AssetItemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoLabel.sizePolicy().hasHeightForWidth())
        self.infoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setTextFormat(QtCore.Qt.PlainText)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.layoutCreateCancel = QtWidgets.QHBoxLayout()
        self.layoutCreateCancel.setObjectName("layoutCreateCancel")
        self.btnCreate = QtWidgets.QPushButton(AssetItemDialog)
        self.btnCreate.setEnabled(False)
        self.btnCreate.setObjectName("btnCreate")
        self.layoutCreateCancel.addWidget(self.btnCreate)
        self.btnCancel = QtWidgets.QPushButton(AssetItemDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.layoutCreateCancel.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.layoutCreateCancel)

        self.retranslateUi(AssetItemDialog)
        QtCore.QMetaObject.connectSlotsByName(AssetItemDialog)

    def retranslateUi(self, AssetItemDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetItemDialog.setWindowTitle(_translate("AssetItemDialog", "Create New Asset Item"))
        self.assetLabel.setText(_translate("AssetItemDialog", "Asset"))
        self.formatLabel.setText(_translate("AssetItemDialog", "Format"))
        self.checkboxCopyIncrement.setText(_translate("AssetItemDialog", "Copy and increment existing Asset Item"))
        self.shortNameLabel.setText(_translate("AssetItemDialog", "Shortname"))
        self.shortNameLineEdit.setToolTip(_translate("AssetItemDialog", "Alphanumeric only"))
        self.versionLabel.setText(_translate("AssetItemDialog", "Version"))
        self.nameLabel.setText(_translate("AssetItemDialog", "Full Name"))
        self.descLabel.setText(_translate("AssetItemDialog", "Description"))
        self.descTextEdit.setPlaceholderText(_translate("AssetItemDialog", "Optional. Max chars 255."))
        self.infoLabel.setText(_translate("AssetItemDialog", "Placeholder"))
        self.btnCreate.setText(_translate("AssetItemDialog", "Create"))
        self.btnCancel.setText(_translate("AssetItemDialog", "Cancel"))
