# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\window\applications_list.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppListDialog(object):
    def setupUi(self, AppListDialog):
        AppListDialog.setObjectName("AppListDialog")
        AppListDialog.resize(480, 360)
        AppListDialog.setMinimumSize(QtCore.QSize(480, 360))
        self.verticalLayout = QtWidgets.QVBoxLayout(AppListDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnPushLayout = QtWidgets.QHBoxLayout()
        self.btnPushLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.btnPushLayout.setSpacing(12)
        self.btnPushLayout.setObjectName("btnPushLayout")
        self.btnPushAdd = QtWidgets.QPushButton(AppListDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushAdd.sizePolicy().hasHeightForWidth())
        self.btnPushAdd.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPushAdd.setIcon(icon)
        self.btnPushAdd.setIconSize(QtCore.QSize(30, 30))
        self.btnPushAdd.setCheckable(False)
        self.btnPushAdd.setDefault(False)
        self.btnPushAdd.setFlat(False)
        self.btnPushAdd.setObjectName("btnPushAdd")
        self.btnPushLayout.addWidget(self.btnPushAdd)
        self.btnPushRemove = QtWidgets.QPushButton(AppListDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushRemove.sizePolicy().hasHeightForWidth())
        self.btnPushRemove.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/minus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPushRemove.setIcon(icon1)
        self.btnPushRemove.setIconSize(QtCore.QSize(30, 30))
        self.btnPushRemove.setCheckable(False)
        self.btnPushRemove.setObjectName("btnPushRemove")
        self.btnPushLayout.addWidget(self.btnPushRemove)
        self.btnPushClear = QtWidgets.QPushButton(AppListDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushClear.sizePolicy().hasHeightForWidth())
        self.btnPushClear.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPushClear.setIcon(icon2)
        self.btnPushClear.setIconSize(QtCore.QSize(30, 30))
        self.btnPushClear.setCheckable(False)
        self.btnPushClear.setObjectName("btnPushClear")
        self.btnPushLayout.addWidget(self.btnPushClear)
        spacerItem = QtWidgets.QSpacerItem(539, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnPushLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.btnPushLayout)
        self.tableAppList = QtWidgets.QTableWidget(AppListDialog)
        self.tableAppList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableAppList.setObjectName("tableAppList")
        self.tableAppList.setColumnCount(2)
        self.tableAppList.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppList.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableAppList)
        self.label = QtWidgets.QLabel(AppListDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.btnExportLayout = QtWidgets.QHBoxLayout()
        self.btnExportLayout.setSpacing(6)
        self.btnExportLayout.setObjectName("btnExportLayout")
        self.btnExportCSV = QtWidgets.QPushButton(AppListDialog)
        self.btnExportCSV.setEnabled(False)
        self.btnExportCSV.setFlat(False)
        self.btnExportCSV.setObjectName("btnExportCSV")
        self.btnExportLayout.addWidget(self.btnExportCSV)
        self.btnExportJSON = QtWidgets.QPushButton(AppListDialog)
        self.btnExportJSON.setEnabled(False)
        self.btnExportJSON.setObjectName("btnExportJSON")
        self.btnExportLayout.addWidget(self.btnExportJSON)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnExportLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.btnExportLayout)
        self.btnDialogBox = QtWidgets.QDialogButtonBox(AppListDialog)
        self.btnDialogBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnDialogBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnDialogBox.setObjectName("btnDialogBox")
        self.verticalLayout.addWidget(self.btnDialogBox)
        self.tableAppList.raise_()
        self.btnDialogBox.raise_()
        self.label.raise_()

        self.retranslateUi(AppListDialog)
        self.btnDialogBox.accepted.connect(AppListDialog.accept)
        self.btnDialogBox.rejected.connect(AppListDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AppListDialog)

    def retranslateUi(self, AppListDialog):
        _translate = QtCore.QCoreApplication.translate
        AppListDialog.setWindowTitle(_translate("AppListDialog", "Applications List"))
        self.btnPushAdd.setToolTip(_translate("AppListDialog", "Add Asset Item Format"))
        self.btnPushRemove.setToolTip(_translate("AppListDialog", "Remove selected Asset Item Formats"))
        self.btnPushClear.setToolTip(_translate("AppListDialog", "Clear all Asset Item Formats"))
        item = self.tableAppList.verticalHeaderItem(0)
        item.setText(_translate("AppListDialog", "1"))
        item = self.tableAppList.horizontalHeaderItem(0)
        item.setText(_translate("AppListDialog", "Name"))
        item = self.tableAppList.horizontalHeaderItem(1)
        item.setText(_translate("AppListDialog", "Application Path"))
        self.label.setText(_translate("AppListDialog", "<html><head/><body><p>Use full path for Application Path.</p><p>E.g. <span style=\" font-weight:600;\">C:\\Program Files\\Autodesk\\Maya2020\\bin\\maya.exe</span></p></body></html>"))
        self.btnExportCSV.setText(_translate("AppListDialog", "  Export to CSV  "))
        self.btnExportJSON.setText(_translate("AppListDialog", "  Export to JSON  "))
from . import icons_rc
