# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\window\asset_item_format.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssetItemFormatDialog(object):
    def setupUi(self, AssetItemFormatDialog):
        AssetItemFormatDialog.setObjectName("AssetItemFormatDialog")
        AssetItemFormatDialog.resize(480, 360)
        AssetItemFormatDialog.setMinimumSize(QtCore.QSize(480, 360))
        self.verticalLayout = QtWidgets.QVBoxLayout(AssetItemFormatDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnPushLayout = QtWidgets.QHBoxLayout()
        self.btnPushLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.btnPushLayout.setSpacing(12)
        self.btnPushLayout.setObjectName("btnPushLayout")
        self.btnPushAdd = QtWidgets.QPushButton(AssetItemFormatDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushAdd.sizePolicy().hasHeightForWidth())
        self.btnPushAdd.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPushAdd.setIcon(icon)
        self.btnPushAdd.setIconSize(QtCore.QSize(30, 30))
        self.btnPushAdd.setCheckable(False)
        self.btnPushAdd.setDefault(False)
        self.btnPushAdd.setFlat(False)
        self.btnPushAdd.setObjectName("btnPushAdd")
        self.btnPushLayout.addWidget(self.btnPushAdd)
        self.btnPushRemove = QtWidgets.QPushButton(AssetItemFormatDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushRemove.sizePolicy().hasHeightForWidth())
        self.btnPushRemove.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/minus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPushRemove.setIcon(icon1)
        self.btnPushRemove.setIconSize(QtCore.QSize(30, 30))
        self.btnPushRemove.setCheckable(False)
        self.btnPushRemove.setObjectName("btnPushRemove")
        self.btnPushLayout.addWidget(self.btnPushRemove)
        self.btnPushClear = QtWidgets.QPushButton(AssetItemFormatDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushClear.sizePolicy().hasHeightForWidth())
        self.btnPushClear.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPushClear.setIcon(icon2)
        self.btnPushClear.setIconSize(QtCore.QSize(30, 30))
        self.btnPushClear.setCheckable(False)
        self.btnPushClear.setObjectName("btnPushClear")
        self.btnPushLayout.addWidget(self.btnPushClear)
        spacerItem = QtWidgets.QSpacerItem(539, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnPushLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.btnPushLayout)
        self.tableAssetItemFormat = QtWidgets.QTableWidget(AssetItemFormatDialog)
        self.tableAssetItemFormat.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableAssetItemFormat.setObjectName("tableAssetItemFormat")
        self.tableAssetItemFormat.setColumnCount(3)
        self.tableAssetItemFormat.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableAssetItemFormat.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAssetItemFormat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAssetItemFormat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAssetItemFormat.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableAssetItemFormat)
        self.label = QtWidgets.QLabel(AssetItemFormatDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.btnExportLayout = QtWidgets.QHBoxLayout()
        self.btnExportLayout.setSpacing(6)
        self.btnExportLayout.setObjectName("btnExportLayout")
        self.btnExportCSV = QtWidgets.QPushButton(AssetItemFormatDialog)
        self.btnExportCSV.setEnabled(False)
        self.btnExportCSV.setFlat(False)
        self.btnExportCSV.setObjectName("btnExportCSV")
        self.btnExportLayout.addWidget(self.btnExportCSV)
        self.btnExportJSON = QtWidgets.QPushButton(AssetItemFormatDialog)
        self.btnExportJSON.setEnabled(False)
        self.btnExportJSON.setObjectName("btnExportJSON")
        self.btnExportLayout.addWidget(self.btnExportJSON)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnExportLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.btnExportLayout)
        self.btnDialogBox = QtWidgets.QDialogButtonBox(AssetItemFormatDialog)
        self.btnDialogBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnDialogBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnDialogBox.setObjectName("btnDialogBox")
        self.verticalLayout.addWidget(self.btnDialogBox)
        self.tableAssetItemFormat.raise_()
        self.btnDialogBox.raise_()
        self.label.raise_()
        self.btnExportCSV.raise_()

        self.retranslateUi(AssetItemFormatDialog)
        self.btnDialogBox.accepted.connect(AssetItemFormatDialog.accept)
        self.btnDialogBox.rejected.connect(AssetItemFormatDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AssetItemFormatDialog)

    def retranslateUi(self, AssetItemFormatDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetItemFormatDialog.setWindowTitle(_translate("AssetItemFormatDialog", "Manage Asset Item Format"))
        self.btnPushAdd.setToolTip(_translate("AssetItemFormatDialog", "Add Asset Item Format"))
        self.btnPushRemove.setToolTip(_translate("AssetItemFormatDialog", "Remove selected Asset Item Formats"))
        self.btnPushClear.setToolTip(_translate("AssetItemFormatDialog", "Clear all Asset Item Formats"))
        item = self.tableAssetItemFormat.verticalHeaderItem(0)
        item.setText(_translate("AssetItemFormatDialog", "1"))
        item = self.tableAssetItemFormat.horizontalHeaderItem(0)
        item.setText(_translate("AssetItemFormatDialog", "Name"))
        item = self.tableAssetItemFormat.horizontalHeaderItem(1)
        item.setText(_translate("AssetItemFormatDialog", "Format"))
        item = self.tableAssetItemFormat.horizontalHeaderItem(2)
        item.setText(_translate("AssetItemFormatDialog", "Application"))
        self.label.setText(_translate("AssetItemFormatDialog", "<html><head/><body><p>Use comma as separator for multiple extensions in Format. Case insensitive.</p><p>E.g. <span style=\" font-weight:600;\">MA,MB</span> or <span style=\" font-weight:600;\">Max</span> or <span style=\" font-weight:600;\">hipnc,hip</span></p></body></html>"))
        self.btnExportCSV.setText(_translate("AssetItemFormatDialog", "  Export to CSV  "))
        self.btnExportJSON.setText(_translate("AssetItemFormatDialog", "  Export to JSON  "))
from . import icons_rc
