# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\window\asset.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AssetDialog(object):
    def setupUi(self, AssetDialog):
        AssetDialog.setObjectName("AssetDialog")
        AssetDialog.resize(350, 470)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssetDialog.sizePolicy().hasHeightForWidth())
        AssetDialog.setSizePolicy(sizePolicy)
        AssetDialog.setMinimumSize(QtCore.QSize(350, 470))
        AssetDialog.setMaximumSize(QtCore.QSize(350, 470))
        AssetDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        AssetDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.layoutVtlDialog = QtWidgets.QVBoxLayout(AssetDialog)
        self.layoutVtlDialog.setObjectName("layoutVtlDialog")
        self.layoutHznAsset = QtWidgets.QHBoxLayout()
        self.layoutHznAsset.setObjectName("layoutHznAsset")
        self.assetLabel = QtWidgets.QLabel(AssetDialog)
        self.assetLabel.setObjectName("assetLabel")
        self.layoutHznAsset.addWidget(self.assetLabel)
        self.assetLineEdit = QtWidgets.QLineEdit(AssetDialog)
        self.assetLineEdit.setMaxLength(3)
        self.assetLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.assetLineEdit.setObjectName("assetLineEdit")
        self.layoutHznAsset.addWidget(self.assetLineEdit)
        self.layoutVtlDialog.addLayout(self.layoutHznAsset)
        self.layoutHznCatDesc = QtWidgets.QHBoxLayout()
        self.layoutHznCatDesc.setObjectName("layoutHznCatDesc")
        self.catGroup = QtWidgets.QGroupBox(AssetDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.catGroup.setFont(font)
        self.catGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.catGroup.setFlat(False)
        self.catGroup.setCheckable(False)
        self.catGroup.setObjectName("catGroup")
        self.layoutVtlCat = QtWidgets.QVBoxLayout(self.catGroup)
        self.layoutVtlCat.setObjectName("layoutVtlCat")
        self.catPlaceholder = QtWidgets.QRadioButton(self.catGroup)
        self.catPlaceholder.setObjectName("catPlaceholder")
        self.catBtnGroup = QtWidgets.QButtonGroup(AssetDialog)
        self.catBtnGroup.setObjectName("catBtnGroup")
        self.catBtnGroup.addButton(self.catPlaceholder)
        self.layoutVtlCat.addWidget(self.catPlaceholder)
        self.layoutHznCatDesc.addWidget(self.catGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.layoutHznCatDesc.addItem(spacerItem)
        self.descGroup = QtWidgets.QGroupBox(AssetDialog)
        self.descGroup.setEnabled(False)
        self.descGroup.setObjectName("descGroup")
        self.layoutVtlDesc = QtWidgets.QVBoxLayout(self.descGroup)
        self.layoutVtlDesc.setObjectName("layoutVtlDesc")
        self.descName = QtWidgets.QLabel(self.descGroup)
        self.descName.setObjectName("descName")
        self.layoutVtlDesc.addWidget(self.descName)
        self.descNameLineEdit = QtWidgets.QLineEdit(self.descGroup)
        self.descNameLineEdit.setObjectName("descNameLineEdit")
        self.layoutVtlDesc.addWidget(self.descNameLineEdit)
        self.descHint = QtWidgets.QLabel(self.descGroup)
        self.descHint.setTextFormat(QtCore.Qt.AutoText)
        self.descHint.setScaledContents(False)
        self.descHint.setWordWrap(True)
        self.descHint.setObjectName("descHint")
        self.layoutVtlDesc.addWidget(self.descHint)
        self.descNameLineEdit.raise_()
        self.descName.raise_()
        self.descHint.raise_()
        self.layoutHznCatDesc.addWidget(self.descGroup)
        self.layoutVtlDialog.addLayout(self.layoutHznCatDesc)
        self.previewLabel = QtWidgets.QLabel(AssetDialog)
        self.previewLabel.setObjectName("previewLabel")
        self.layoutVtlDialog.addWidget(self.previewLabel)
        self.previewGroup = QtWidgets.QGroupBox(AssetDialog)
        self.previewGroup.setCheckable(True)
        self.previewGroup.setChecked(False)
        self.previewGroup.setObjectName("previewGroup")
        self.layoutVtlPreview = QtWidgets.QVBoxLayout(self.previewGroup)
        self.layoutVtlPreview.setObjectName("layoutVtlPreview")
        self.previewText = QtWidgets.QPlainTextEdit(self.previewGroup)
        self.previewText.setReadOnly(True)
        self.previewText.setObjectName("previewText")
        self.layoutVtlPreview.addWidget(self.previewText)
        self.layoutVtlDialog.addWidget(self.previewGroup)
        self.layoutHznBtn = QtWidgets.QHBoxLayout()
        self.layoutHznBtn.setObjectName("layoutHznBtn")
        self.btnCreate = QtWidgets.QPushButton(AssetDialog)
        self.btnCreate.setObjectName("btnCreate")
        self.layoutHznBtn.addWidget(self.btnCreate)
        self.btnCancel = QtWidgets.QPushButton(AssetDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.layoutHznBtn.addWidget(self.btnCancel)
        self.layoutVtlDialog.addLayout(self.layoutHznBtn)
        self.previewGroup.raise_()
        self.previewLabel.raise_()

        self.retranslateUi(AssetDialog)
        QtCore.QMetaObject.connectSlotsByName(AssetDialog)

    def retranslateUi(self, AssetDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetDialog.setWindowTitle(_translate("AssetDialog", "Create New Asset"))
        self.assetLabel.setText(_translate("AssetDialog", "Asset Name (max 3 characters) :"))
        self.assetLineEdit.setToolTip(_translate("AssetDialog", "Alphanumeric only"))
        self.catGroup.setTitle(_translate("AssetDialog", "Category"))
        self.catPlaceholder.setText(_translate("AssetDialog", "Placeholder"))
        self.descGroup.setTitle(_translate("AssetDialog", "Description (disabled)"))
        self.descName.setText(_translate("AssetDialog", "Full Name:"))
        self.descHint.setText(_translate("AssetDialog", "<html><head/><body><p>Remember to write meaningful Full Name for easy identification. E.g.:</p><p>HSE - House<br/>PAU - Pope\'s Aura Flame</p></body></html>"))
        self.previewLabel.setText(_translate("AssetDialog", "*Preview must be checked to enable Create"))
        self.previewGroup.setTitle(_translate("AssetDialog", "Preview"))
        self.btnCreate.setText(_translate("AssetDialog", "Create"))
        self.btnCancel.setText(_translate("AssetDialog", "Cancel"))

