# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\window\preferences.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PrefsDialog(object):
    def setupUi(self, PrefsDialog):
        PrefsDialog.setObjectName("PrefsDialog")
        PrefsDialog.setEnabled(True)
        PrefsDialog.resize(518, 579)
        PrefsDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        PrefsDialog.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        PrefsDialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(PrefsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.sideLayout = QtWidgets.QVBoxLayout()
        self.sideLayout.setObjectName("sideLayout")
        self.sideList = QtWidgets.QListWidget(PrefsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideList.sizePolicy().hasHeightForWidth())
        self.sideList.setSizePolicy(sizePolicy)
        self.sideList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sideList.setObjectName("sideList")
        item = QtWidgets.QListWidgetItem()
        self.sideList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sideList.addItem(item)
        self.sideLayout.addWidget(self.sideList)
        self.gridLayout.addLayout(self.sideLayout, 3, 0, 2, 1)
        self.btnDialogBox = QtWidgets.QDialogButtonBox(PrefsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDialogBox.sizePolicy().hasHeightForWidth())
        self.btnDialogBox.setSizePolicy(sizePolicy)
        self.btnDialogBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnDialogBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.btnDialogBox.setCenterButtons(False)
        self.btnDialogBox.setObjectName("btnDialogBox")
        self.gridLayout.addWidget(self.btnDialogBox, 5, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(PrefsDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageSettings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSettings.sizePolicy().hasHeightForWidth())
        self.pageSettings.setSizePolicy(sizePolicy)
        self.pageSettings.setObjectName("pageSettings")
        self.formLayout = QtWidgets.QFormLayout(self.pageSettings)
        self.formLayout.setObjectName("formLayout")
        self.themeLabel = QtWidgets.QLabel(self.pageSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themeLabel.sizePolicy().hasHeightForWidth())
        self.themeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.themeLabel.setFont(font)
        self.themeLabel.setObjectName("themeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.themeLabel)
        self.themeRadioLight = QtWidgets.QRadioButton(self.pageSettings)
        self.themeRadioLight.setShortcut("")
        self.themeRadioLight.setChecked(True)
        self.themeRadioLight.setObjectName("themeRadioLight")
        self.themeBtnGroup = QtWidgets.QButtonGroup(PrefsDialog)
        self.themeBtnGroup.setObjectName("themeBtnGroup")
        self.themeBtnGroup.addButton(self.themeRadioLight)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.themeRadioLight)
        self.themeRadioDark = QtWidgets.QRadioButton(self.pageSettings)
        self.themeRadioDark.setShortcut("")
        self.themeRadioDark.setObjectName("themeRadioDark")
        self.themeBtnGroup.addButton(self.themeRadioDark)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.themeRadioDark)
        self.projectPathLayout = QtWidgets.QHBoxLayout()
        self.projectPathLayout.setObjectName("projectPathLayout")
        self.projectPathLabel = QtWidgets.QLabel(self.pageSettings)
        self.projectPathLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.projectPathLabel.setObjectName("projectPathLabel")
        self.projectPathLayout.addWidget(self.projectPathLabel)
        self.projectPathLine = QtWidgets.QLineEdit(self.pageSettings)
        self.projectPathLine.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.projectPathLine.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.projectPathLine.setDragEnabled(False)
        self.projectPathLine.setPlaceholderText("")
        self.projectPathLine.setObjectName("projectPathLine")
        self.projectPathLayout.addWidget(self.projectPathLine)
        self.projectPathTool = QtWidgets.QToolButton(self.pageSettings)
        self.projectPathTool.setAutoRaise(False)
        self.projectPathTool.setArrowType(QtCore.Qt.NoArrow)
        self.projectPathTool.setObjectName("projectPathTool")
        self.projectPathLayout.addWidget(self.projectPathTool)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.projectPathLayout)
        self.checkDebug = QtWidgets.QCheckBox(self.pageSettings)
        self.checkDebug.setObjectName("checkDebug")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.checkDebug)
        self.checkDesc = QtWidgets.QCheckBox(self.pageSettings)
        self.checkDesc.setObjectName("checkDesc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.checkDesc)
        self.stackedWidget.addWidget(self.pageSettings)
        self.pageAssets = QtWidgets.QWidget()
        self.pageAssets.setObjectName("pageAssets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageAssets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.boxNaming = QtWidgets.QGroupBox(self.pageAssets)
        self.boxNaming.setObjectName("boxNaming")
        self.formLayout_3 = QtWidgets.QFormLayout(self.boxNaming)
        self.formLayout_3.setObjectName("formLayout_3")
        self.maxCharLayout = QtWidgets.QFormLayout()
        self.maxCharLayout.setObjectName("maxCharLayout")
        self.maxCharLabel = QtWidgets.QLabel(self.boxNaming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxCharLabel.sizePolicy().hasHeightForWidth())
        self.maxCharLabel.setSizePolicy(sizePolicy)
        self.maxCharLabel.setObjectName("maxCharLabel")
        self.maxCharLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.maxCharLabel)
        self.maxCharSpinner = QtWidgets.QSpinBox(self.boxNaming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxCharSpinner.sizePolicy().hasHeightForWidth())
        self.maxCharSpinner.setSizePolicy(sizePolicy)
        self.maxCharSpinner.setMinimum(3)
        self.maxCharSpinner.setObjectName("maxCharSpinner")
        self.maxCharLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxCharSpinner)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.maxCharLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.separatorLabel = QtWidgets.QLabel(self.boxNaming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separatorLabel.sizePolicy().hasHeightForWidth())
        self.separatorLabel.setSizePolicy(sizePolicy)
        self.separatorLabel.setObjectName("separatorLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.separatorLabel)
        self.separatorCombo = QtWidgets.QComboBox(self.boxNaming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separatorCombo.sizePolicy().hasHeightForWidth())
        self.separatorCombo.setSizePolicy(sizePolicy)
        self.separatorCombo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.separatorCombo.setObjectName("separatorCombo")
        self.separatorCombo.addItem("")
        self.separatorCombo.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.separatorCombo)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_2)
        self.boxPrefix = QtWidgets.QGroupBox(self.boxNaming)
        self.boxPrefix.setCheckable(True)
        self.boxPrefix.setObjectName("boxPrefix")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.boxPrefix)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioPrefix1 = QtWidgets.QRadioButton(self.boxPrefix)
        self.radioPrefix1.setChecked(True)
        self.radioPrefix1.setObjectName("radioPrefix1")
        self.verticalLayout.addWidget(self.radioPrefix1)
        self.radioPrefix2 = QtWidgets.QRadioButton(self.boxPrefix)
        self.radioPrefix2.setChecked(False)
        self.radioPrefix2.setObjectName("radioPrefix2")
        self.verticalLayout.addWidget(self.radioPrefix2)
        self.radioPrefix3 = QtWidgets.QRadioButton(self.boxPrefix)
        self.radioPrefix3.setObjectName("radioPrefix3")
        self.verticalLayout.addWidget(self.radioPrefix3)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.boxPrefix)
        self.boxSuffix = QtWidgets.QGroupBox(self.boxNaming)
        self.boxSuffix.setCheckable(True)
        self.boxSuffix.setObjectName("boxSuffix")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.boxSuffix)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verVersioningLayout = QtWidgets.QFormLayout()
        self.verVersioningLayout.setObjectName("verVersioningLayout")
        self.radioSuffix1 = QtWidgets.QRadioButton(self.boxSuffix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSuffix1.sizePolicy().hasHeightForWidth())
        self.radioSuffix1.setSizePolicy(sizePolicy)
        self.radioSuffix1.setChecked(True)
        self.radioSuffix1.setObjectName("radioSuffix1")
        self.verVersioningLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioSuffix1)
        self.verVersioningCombo = QtWidgets.QComboBox(self.boxSuffix)
        self.verVersioningCombo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.verVersioningCombo.setObjectName("verVersioningCombo")
        self.verVersioningCombo.addItem("")
        self.verVersioningCombo.addItem("")
        self.verVersioningLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.verVersioningCombo)
        self.verticalLayout_2.addLayout(self.verVersioningLayout)
        self.verCustomLayout = QtWidgets.QHBoxLayout()
        self.verCustomLayout.setObjectName("verCustomLayout")
        self.radioSuffix2 = QtWidgets.QRadioButton(self.boxSuffix)
        self.radioSuffix2.setObjectName("radioSuffix2")
        self.verCustomLayout.addWidget(self.radioSuffix2)
        self.verCustomName = QtWidgets.QLineEdit(self.boxSuffix)
        self.verCustomName.setObjectName("verCustomName")
        self.verCustomLayout.addWidget(self.verCustomName)
        self.verticalLayout_2.addLayout(self.verCustomLayout)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.boxSuffix)
        self.verticalLayout_3.addWidget(self.boxNaming)
        self.boxCategory = QtWidgets.QGroupBox(self.pageAssets)
        self.boxCategory.setObjectName("boxCategory")
        self.formLayout_4 = QtWidgets.QFormLayout(self.boxCategory)
        self.formLayout_4.setObjectName("formLayout_4")
        self.categoryBtnLayout = QtWidgets.QFormLayout()
        self.categoryBtnLayout.setObjectName("categoryBtnLayout")
        self.categoryBtnAdd = QtWidgets.QPushButton(self.boxCategory)
        self.categoryBtnAdd.setObjectName("categoryBtnAdd")
        self.categoryBtnLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.categoryBtnAdd)
        self.categoryBtnRemove = QtWidgets.QPushButton(self.boxCategory)
        self.categoryBtnRemove.setObjectName("categoryBtnRemove")
        self.categoryBtnLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.categoryBtnRemove)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.categoryBtnLayout)
        self.categoryList = QtWidgets.QListWidget(self.boxCategory)
        self.categoryList.setObjectName("categoryList")
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.categoryList)
        self.verticalLayout_3.addWidget(self.boxCategory)
        self.stackedWidget.addWidget(self.pageAssets)
        self.pageAdvanced = QtWidgets.QWidget()
        self.pageAdvanced.setObjectName("pageAdvanced")
        self.stackedWidget.addWidget(self.pageAdvanced)
        self.gridLayout.addWidget(self.stackedWidget, 4, 1, 1, 1)

        self.retranslateUi(PrefsDialog)
        self.stackedWidget.setCurrentIndex(0)
        self.sideList.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.radioSuffix1.toggled['bool'].connect(self.verVersioningCombo.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PrefsDialog)

    def retranslateUi(self, PrefsDialog):
        _translate = QtCore.QCoreApplication.translate
        PrefsDialog.setWindowTitle(_translate("PrefsDialog", "Preferences"))
        __sortingEnabled = self.sideList.isSortingEnabled()
        self.sideList.setSortingEnabled(False)
        item = self.sideList.item(0)
        item.setText(_translate("PrefsDialog", "Settings"))
        item = self.sideList.item(1)
        item.setText(_translate("PrefsDialog", "Assets"))
        item = self.sideList.item(2)
        item.setText(_translate("PrefsDialog", "Advanced"))
        self.sideList.setSortingEnabled(__sortingEnabled)
        self.themeLabel.setText(_translate("PrefsDialog", "Theme:"))
        self.themeRadioLight.setText(_translate("PrefsDialog", "Default (Light)"))
        self.themeRadioDark.setText(_translate("PrefsDialog", "Dark"))
        self.projectPathLabel.setText(_translate("PrefsDialog", "Project Path:"))
        self.projectPathLine.setToolTip(_translate("PrefsDialog", "Insert your project path here. E.g. \"P:/\", \"media/projects\""))
        self.projectPathTool.setToolTip(_translate("PrefsDialog", "Choose directory"))
        self.projectPathTool.setText(_translate("PrefsDialog", "..."))
        self.checkDebug.setToolTip(_translate("PrefsDialog", "Log file will be stored in log directory."))
        self.checkDebug.setText(_translate("PrefsDialog", "Enable Debug Log"))
        self.checkDesc.setToolTip(_translate("PrefsDialog", "Display description for selected assets."))
        self.checkDesc.setText(_translate("PrefsDialog", "Show Description Panel"))
        self.boxNaming.setTitle(_translate("PrefsDialog", "Naming Convention"))
        self.maxCharLabel.setText(_translate("PrefsDialog", "Max characters:"))
        self.maxCharSpinner.setToolTip(_translate("PrefsDialog", "Min: 3, Max: 99"))
        self.separatorLabel.setText(_translate("PrefsDialog", "Separator:"))
        self.separatorCombo.setItemText(0, _translate("PrefsDialog", " _ (underscore)"))
        self.separatorCombo.setItemText(1, _translate("PrefsDialog", " - (dash)"))
        self.boxPrefix.setTitle(_translate("PrefsDialog", "Prefix"))
        self.radioPrefix1.setText(_translate("PrefsDialog", "Use first character of category (e.g.: p)"))
        self.radioPrefix2.setText(_translate("PrefsDialog", "Use whole category (e.g.: props)"))
        self.radioPrefix3.setText(_translate("PrefsDialog", "Use custom naming (JSON mapping)"))
        self.boxSuffix.setTitle(_translate("PrefsDialog", "Suffix"))
        self.radioSuffix1.setText(_translate("PrefsDialog", "Use versioning (v):"))
        self.verVersioningCombo.setItemText(0, _translate("PrefsDialog", "lowercase (v001)"))
        self.verVersioningCombo.setItemText(1, _translate("PrefsDialog", "UPPERCASE (V001)"))
        self.radioSuffix2.setText(_translate("PrefsDialog", "Use custom naming:"))
        self.boxCategory.setTitle(_translate("PrefsDialog", "Categories"))
        self.categoryBtnAdd.setText(_translate("PrefsDialog", "Add"))
        self.categoryBtnRemove.setText(_translate("PrefsDialog", "Remove"))
        __sortingEnabled = self.categoryList.isSortingEnabled()
        self.categoryList.setSortingEnabled(False)
        item = self.categoryList.item(0)
        item.setText(_translate("PrefsDialog", "BG"))
        item = self.categoryList.item(1)
        item.setText(_translate("PrefsDialog", "CH"))
        item = self.categoryList.item(2)
        item.setText(_translate("PrefsDialog", "FX"))
        item = self.categoryList.item(3)
        item.setText(_translate("PrefsDialog", "Props"))
        item = self.categoryList.item(4)
        item.setText(_translate("PrefsDialog", "Vehicles"))
        self.categoryList.setSortingEnabled(__sortingEnabled)

