# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\asset.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AssetDialog(object):
    def setupUi(self, AssetDialog):
        AssetDialog.setObjectName("AssetDialog")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssetDialog.sizePolicy().hasHeightForWidth())
        AssetDialog.setSizePolicy(sizePolicy)
        AssetDialog.setMinimumSize(QtCore.QSize(350, 470))
        AssetDialog.setMaximumSize(QtCore.QSize(350, 470))
        AssetDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        AssetDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AssetDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.assetLabel = QtWidgets.QLabel(AssetDialog)
        self.assetLabel.setObjectName("assetLabel")
        self.horizontalLayout.addWidget(self.assetLabel)
        self.assetLineEdit = QtWidgets.QLineEdit(AssetDialog)
        self.assetLineEdit.setMaxLength(3)
        self.assetLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.assetLineEdit.setObjectName("assetLineEdit")
        self.horizontalLayout.addWidget(self.assetLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.catGroup = QtWidgets.QGroupBox(AssetDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.catGroup.setFont(font)
        self.catGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.catGroup.setFlat(False)
        self.catGroup.setCheckable(False)
        self.catGroup.setObjectName("catGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.catGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.catBG = QtWidgets.QRadioButton(self.catGroup)
        self.catBG.setObjectName("catBG")
        self.catBtnGroup = QtWidgets.QButtonGroup(AssetDialog)
        self.catBtnGroup.setObjectName("catBtnGroup")
        self.catBtnGroup.addButton(self.catBG)
        self.verticalLayout_3.addWidget(self.catBG)
        self.catCH = QtWidgets.QRadioButton(self.catGroup)
        self.catCH.setObjectName("catCH")
        self.catBtnGroup.addButton(self.catCH)
        self.verticalLayout_3.addWidget(self.catCH)
        self.catFX = QtWidgets.QRadioButton(self.catGroup)
        self.catFX.setObjectName("catFX")
        self.catBtnGroup.addButton(self.catFX)
        self.verticalLayout_3.addWidget(self.catFX)
        self.catProps = QtWidgets.QRadioButton(self.catGroup)
        self.catProps.setObjectName("catProps")
        self.catBtnGroup.addButton(self.catProps)
        self.verticalLayout_3.addWidget(self.catProps)
        self.catVehicles = QtWidgets.QRadioButton(self.catGroup)
        self.catVehicles.setObjectName("catVehicles")
        self.catBtnGroup.addButton(self.catVehicles)
        self.verticalLayout_3.addWidget(self.catVehicles)
        self.horizontalLayout_3.addWidget(self.catGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.horizontalLayout_3.addItem(spacerItem)
        self.descGroup = QtWidgets.QGroupBox(AssetDialog)
        self.descGroup.setEnabled(False)
        self.descGroup.setObjectName("descGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.descGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.descName = QtWidgets.QLabel(self.descGroup)
        self.descName.setObjectName("descName")
        self.verticalLayout_4.addWidget(self.descName)
        self.descNameLineEdit = QtWidgets.QLineEdit(self.descGroup)
        self.descNameLineEdit.setObjectName("descNameLineEdit")
        self.verticalLayout_4.addWidget(self.descNameLineEdit)
        self.descHint = QtWidgets.QLabel(self.descGroup)
        self.descHint.setTextFormat(QtCore.Qt.AutoText)
        self.descHint.setScaledContents(False)
        self.descHint.setWordWrap(True)
        self.descHint.setObjectName("descHint")
        self.verticalLayout_4.addWidget(self.descHint)
        self.descNameLineEdit.raise_()
        self.descName.raise_()
        self.descHint.raise_()
        self.horizontalLayout_3.addWidget(self.descGroup)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.previewLabel = QtWidgets.QLabel(AssetDialog)
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout_2.addWidget(self.previewLabel)
        self.previewGroup = QtWidgets.QGroupBox(AssetDialog)
        self.previewGroup.setCheckable(True)
        self.previewGroup.setChecked(False)
        self.previewGroup.setObjectName("previewGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.previewGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.previewText = QtWidgets.QPlainTextEdit(self.previewGroup)
        self.previewText.setReadOnly(True)
        self.previewText.setObjectName("previewText")
        self.verticalLayout.addWidget(self.previewText)
        self.verticalLayout_2.addWidget(self.previewGroup)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCreate = QtWidgets.QPushButton(AssetDialog)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout_2.addWidget(self.btnCreate)
        self.btnCancel = QtWidgets.QPushButton(AssetDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.previewGroup.raise_()
        self.previewLabel.raise_()

        self.retranslateUi(AssetDialog)
        QtCore.QMetaObject.connectSlotsByName(AssetDialog)

    def retranslateUi(self, AssetDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetDialog.setWindowTitle(_translate("AssetDialog", "Create New Asset"))
        self.assetLabel.setText(_translate("AssetDialog", "Asset Name (max 3 characters) :"))
        self.assetLineEdit.setToolTip(_translate("AssetDialog", "Alphanumeric only"))
        self.catGroup.setTitle(_translate("AssetDialog", "Category"))
        self.catBG.setText(_translate("AssetDialog", "BG"))
        self.catCH.setText(_translate("AssetDialog", "CH"))
        self.catFX.setText(_translate("AssetDialog", "FX"))
        self.catProps.setText(_translate("AssetDialog", "Props"))
        self.catVehicles.setText(_translate("AssetDialog", "Vehicles"))
        self.descGroup.setTitle(_translate("AssetDialog", "Description (disabled)"))
        self.descName.setText(_translate("AssetDialog", "Full Name:"))
        self.descHint.setText(_translate("AssetDialog", "<html><head/><body><p>Remember to write meaningful Full Name for easy identification. E.g.:</p><p>HSE - House<br/>PAU - Pope\'s Aura Flame</p></body></html>"))
        self.previewLabel.setText(_translate("AssetDialog", "*Preview must be checked to enable Create"))
        self.previewGroup.setTitle(_translate("AssetDialog", "Preview"))
        self.btnCreate.setText(_translate("AssetDialog", "Create"))
        self.btnCancel.setText(_translate("AssetDialog", "Cancel"))

