# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\asset.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AssetDialog(object):
    def setupUi(self, AssetDialog):
        AssetDialog.setObjectName("AssetDialog")
        AssetDialog.resize(320, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AssetDialog.sizePolicy().hasHeightForWidth())
        AssetDialog.setSizePolicy(sizePolicy)
        AssetDialog.setMinimumSize(QtCore.QSize(320, 440))
        AssetDialog.setMaximumSize(QtCore.QSize(320, 440))
        self.catGroup = QtWidgets.QGroupBox(AssetDialog)
        self.catGroup.setGeometry(QtCore.QRect(10, 70, 80, 161))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.catGroup.setFont(font)
        self.catGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.catGroup.setFlat(False)
        self.catGroup.setCheckable(False)
        self.catGroup.setObjectName("catGroup")
        self.catBG = QtWidgets.QRadioButton(self.catGroup)
        self.catBG.setGeometry(QtCore.QRect(10, 26, 36, 17))
        self.catBG.setObjectName("catBG")
        self.catBtnGroup = QtWidgets.QButtonGroup(AssetDialog)
        self.catBtnGroup.setObjectName("catBtnGroup")
        self.catBtnGroup.addButton(self.catBG)
        self.catCH = QtWidgets.QRadioButton(self.catGroup)
        self.catCH.setGeometry(QtCore.QRect(10, 52, 37, 17))
        self.catCH.setObjectName("catCH")
        self.catBtnGroup.addButton(self.catCH)
        self.catFX = QtWidgets.QRadioButton(self.catGroup)
        self.catFX.setGeometry(QtCore.QRect(10, 78, 35, 17))
        self.catFX.setObjectName("catFX")
        self.catBtnGroup.addButton(self.catFX)
        self.catProps = QtWidgets.QRadioButton(self.catGroup)
        self.catProps.setGeometry(QtCore.QRect(10, 104, 50, 17))
        self.catProps.setObjectName("catProps")
        self.catBtnGroup.addButton(self.catProps)
        self.catVehicles = QtWidgets.QRadioButton(self.catGroup)
        self.catVehicles.setGeometry(QtCore.QRect(10, 130, 60, 17))
        self.catVehicles.setObjectName("catVehicles")
        self.catBtnGroup.addButton(self.catVehicles)
        self.previewGroup = QtWidgets.QGroupBox(AssetDialog)
        self.previewGroup.setGeometry(QtCore.QRect(10, 270, 291, 120))
        self.previewGroup.setCheckable(True)
        self.previewGroup.setChecked(False)
        self.previewGroup.setObjectName("previewGroup")
        self.previewText = QtWidgets.QPlainTextEdit(self.previewGroup)
        self.previewText.setGeometry(QtCore.QRect(10, 20, 271, 90))
        self.previewText.setReadOnly(True)
        self.previewText.setObjectName("previewText")
        self.descGroup = QtWidgets.QGroupBox(AssetDialog)
        self.descGroup.setEnabled(False)
        self.descGroup.setGeometry(QtCore.QRect(100, 70, 201, 161))
        self.descGroup.setObjectName("descGroup")
        self.descNameLineEdit = QtWidgets.QLineEdit(self.descGroup)
        self.descNameLineEdit.setGeometry(QtCore.QRect(20, 40, 171, 21))
        self.descNameLineEdit.setObjectName("descNameLineEdit")
        self.descName = QtWidgets.QLabel(self.descGroup)
        self.descName.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.descName.setObjectName("descName")
        self.descHint = QtWidgets.QLabel(self.descGroup)
        self.descHint.setGeometry(QtCore.QRect(20, 72, 171, 71))
        self.descHint.setTextFormat(QtCore.Qt.AutoText)
        self.descHint.setScaledContents(False)
        self.descHint.setWordWrap(True)
        self.descHint.setObjectName("descHint")
        self.assetLabel = QtWidgets.QLabel(AssetDialog)
        self.assetLabel.setGeometry(QtCore.QRect(20, 30, 158, 16))
        self.assetLabel.setObjectName("assetLabel")
        self.assetLineEdit = QtWidgets.QLineEdit(AssetDialog)
        self.assetLineEdit.setGeometry(QtCore.QRect(190, 30, 101, 20))
        self.assetLineEdit.setMaxLength(3)
        self.assetLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.assetLineEdit.setObjectName("assetLineEdit")
        self.btnCreate = QtWidgets.QPushButton(AssetDialog)
        self.btnCreate.setGeometry(QtCore.QRect(141, 400, 75, 23))
        self.btnCreate.setObjectName("btnCreate")
        self.btnCancel = QtWidgets.QPushButton(AssetDialog)
        self.btnCancel.setGeometry(QtCore.QRect(222, 400, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.previewLabel = QtWidgets.QLabel(AssetDialog)
        self.previewLabel.setGeometry(QtCore.QRect(20, 240, 271, 21))
        self.previewLabel.setObjectName("previewLabel")
        self.catGroup.raise_()
        self.previewGroup.raise_()
        self.descGroup.raise_()
        self.assetLineEdit.raise_()
        self.assetLabel.raise_()
        self.btnCreate.raise_()
        self.btnCancel.raise_()
        self.previewLabel.raise_()

        self.retranslateUi(AssetDialog)
        QtCore.QMetaObject.connectSlotsByName(AssetDialog)

    def retranslateUi(self, AssetDialog):
        _translate = QtCore.QCoreApplication.translate
        AssetDialog.setWindowTitle(_translate("AssetDialog", "Create New Asset"))
        self.catGroup.setTitle(_translate("AssetDialog", "Category"))
        self.catBG.setText(_translate("AssetDialog", "BG"))
        self.catCH.setText(_translate("AssetDialog", "CH"))
        self.catFX.setText(_translate("AssetDialog", "FX"))
        self.catProps.setText(_translate("AssetDialog", "Props"))
        self.catVehicles.setText(_translate("AssetDialog", "Vehicles"))
        self.previewGroup.setTitle(_translate("AssetDialog", "Preview"))
        self.descGroup.setTitle(_translate("AssetDialog", "Description (disabled)"))
        self.descName.setText(_translate("AssetDialog", "Full Name:"))
        self.descHint.setText(_translate("AssetDialog", "<html><head/><body><p>Remember to write meaningful Full Name for easy identification. E.g.:</p><p>HSE - House<br/>PAU - Pope\'s Aura Flame</p></body></html>"))
        self.assetLabel.setText(_translate("AssetDialog", "Asset Name (max 3 characters) :"))
        self.assetLineEdit.setToolTip(_translate("AssetDialog", "Alphanumeric only"))
        self.btnCreate.setText(_translate("AssetDialog", "Create"))
        self.btnCancel.setText(_translate("AssetDialog", "Cancel"))
        self.previewLabel.setText(_translate("AssetDialog", "*Preview must be checked to enable Create"))

