# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(800, 550))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.actionWidget = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionWidget.sizePolicy().hasHeightForWidth())
        self.actionWidget.setSizePolicy(sizePolicy)
        self.actionWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.actionWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.actionWidget.setObjectName(_fromUtf8("actionWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.actionWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelProject = QtGui.QLabel(self.actionWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelProject.setFont(font)
        self.labelProject.setObjectName(_fromUtf8("labelProject"))
        self.verticalLayout.addWidget(self.labelProject)
        self.comboBox = QtGui.QComboBox(self.actionWidget)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout.addWidget(self.comboBox)
        self.pushBtnNew = QtGui.QPushButton(self.actionWidget)
        self.pushBtnNew.setObjectName(_fromUtf8("pushBtnNew"))
        self.verticalLayout.addWidget(self.pushBtnNew)
        self.checkBoxDebug = QtGui.QCheckBox(self.actionWidget)
        self.checkBoxDebug.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxDebug.sizePolicy().hasHeightForWidth())
        self.checkBoxDebug.setSizePolicy(sizePolicy)
        self.checkBoxDebug.setObjectName(_fromUtf8("checkBoxDebug"))
        self.verticalLayout.addWidget(self.checkBoxDebug)
        self.textEdit = QtGui.QTextEdit(self.actionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelCredits = QtGui.QLabel(self.actionWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelCredits.setFont(font)
        self.labelCredits.setTextFormat(QtCore.Qt.AutoText)
        self.labelCredits.setObjectName(_fromUtf8("labelCredits"))
        self.verticalLayout.addWidget(self.labelCredits)
        self.labelCredits.raise_()
        self.checkBoxDebug.raise_()
        self.pushBtnNew.raise_()
        self.labelProject.raise_()
        self.textEdit.raise_()
        self.comboBox.raise_()
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabBG = QtGui.QWidget()
        self.tabBG.setObjectName(_fromUtf8("tabBG"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabBG)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.columnViewBG = QtGui.QColumnView(self.tabBG)
        self.columnViewBG.setAlternatingRowColors(False)
        self.columnViewBG.setResizeGripsVisible(True)
        self.columnViewBG.setObjectName(_fromUtf8("columnViewBG"))
        self.horizontalLayout_6.addWidget(self.columnViewBG)
        self.tabWidget.addTab(self.tabBG, _fromUtf8(""))
        self.tabCH = QtGui.QWidget()
        self.tabCH.setObjectName(_fromUtf8("tabCH"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabCH)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.columnViewCH = QtGui.QColumnView(self.tabCH)
        self.columnViewCH.setAlternatingRowColors(False)
        self.columnViewCH.setResizeGripsVisible(True)
        self.columnViewCH.setObjectName(_fromUtf8("columnViewCH"))
        self.horizontalLayout_5.addWidget(self.columnViewCH)
        self.tabWidget.addTab(self.tabCH, _fromUtf8(""))
        self.tabFX = QtGui.QWidget()
        self.tabFX.setObjectName(_fromUtf8("tabFX"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabFX)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.columnViewFX = QtGui.QColumnView(self.tabFX)
        self.columnViewFX.setAlternatingRowColors(False)
        self.columnViewFX.setResizeGripsVisible(True)
        self.columnViewFX.setObjectName(_fromUtf8("columnViewFX"))
        self.horizontalLayout_4.addWidget(self.columnViewFX)
        self.tabWidget.addTab(self.tabFX, _fromUtf8(""))
        self.tabProps = QtGui.QWidget()
        self.tabProps.setObjectName(_fromUtf8("tabProps"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabProps)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.columnViewProps = QtGui.QColumnView(self.tabProps)
        self.columnViewProps.setAlternatingRowColors(False)
        self.columnViewProps.setResizeGripsVisible(True)
        self.columnViewProps.setObjectName(_fromUtf8("columnViewProps"))
        self.horizontalLayout_7.addWidget(self.columnViewProps)
        self.tabWidget.addTab(self.tabProps, _fromUtf8(""))
        self.tabVehicles = QtGui.QWidget()
        self.tabVehicles.setObjectName(_fromUtf8("tabVehicles"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabVehicles)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.columnViewVehicles = QtGui.QColumnView(self.tabVehicles)
        self.columnViewVehicles.setAlternatingRowColors(False)
        self.columnViewVehicles.setResizeGripsVisible(True)
        self.columnViewVehicles.setObjectName(_fromUtf8("columnViewVehicles"))
        self.horizontalLayout_8.addWidget(self.columnViewVehicles)
        self.tabWidget.addTab(self.tabVehicles, _fromUtf8(""))
        self.tabHelp = QtGui.QWidget()
        self.tabHelp.setObjectName(_fromUtf8("tabHelp"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabHelp)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frameHelp = QtGui.QFrame(self.tabHelp)
        self.frameHelp.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHelp.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameHelp.setObjectName(_fromUtf8("frameHelp"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frameHelp)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelHelp = QtGui.QLabel(self.frameHelp)
        self.labelHelp.setFrameShape(QtGui.QFrame.Box)
        self.labelHelp.setFrameShadow(QtGui.QFrame.Raised)
        self.labelHelp.setLineWidth(1)
        self.labelHelp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHelp.setWordWrap(True)
        self.labelHelp.setObjectName(_fromUtf8("labelHelp"))
        self.horizontalLayout.addWidget(self.labelHelp)
        self.horizontalLayout_3.addWidget(self.frameHelp)
        self.tabWidget.addTab(self.tabHelp, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAlwaysOnTop = QtGui.QAction(MainWindow)
        self.actionAlwaysOnTop.setCheckable(True)
        self.actionAlwaysOnTop.setObjectName(_fromUtf8("actionAlwaysOnTop"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionAlwaysOnTop)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Assets Browser", None))
        self.labelProject.setText(_translate("MainWindow", "Project:", None))
        self.pushBtnNew.setText(_translate("MainWindow", "Create New Asset", None))
        self.checkBoxDebug.setText(_translate("MainWindow", "Show Debug Panel", None))
        self.labelCredits.setText(_translate("MainWindow", "<html><head/><body><p>Huey Yeng © 2017<br/><a href=\"http://taukeke.com\"><span style=\" text-decoration: underline; color:#0000ff;\">http://taukeke.com</span></a></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBG), _translate("MainWindow", "BG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCH), _translate("MainWindow", "CH", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFX), _translate("MainWindow", "FX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProps), _translate("MainWindow", "Props", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVehicles), _translate("MainWindow", "Vehicles", None))
        self.labelHelp.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("MainWindow", "Help", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuView.setTitle(_translate("MainWindow", "&View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "&About Assets Browser", None))
        self.actionAlwaysOnTop.setText(_translate("MainWindow", "Always on &Top", None))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences...", None))

