# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Library\Python\AssetsBrowser\ui\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(180, 10, 600, 540))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabBG = QtGui.QWidget()
        self.tabBG.setObjectName(_fromUtf8("tabBG"))
        self.columnViewBG = QtGui.QColumnView(self.tabBG)
        self.columnViewBG.setGeometry(QtCore.QRect(16, 10, 560, 490))
        self.columnViewBG.setAlternatingRowColors(False)
        self.columnViewBG.setResizeGripsVisible(True)
        self.columnViewBG.setObjectName(_fromUtf8("columnViewBG"))
        self.tabWidget.addTab(self.tabBG, _fromUtf8(""))
        self.tabCH = QtGui.QWidget()
        self.tabCH.setObjectName(_fromUtf8("tabCH"))
        self.columnViewCH = QtGui.QColumnView(self.tabCH)
        self.columnViewCH.setGeometry(QtCore.QRect(16, 10, 560, 490))
        self.columnViewCH.setAlternatingRowColors(False)
        self.columnViewCH.setResizeGripsVisible(True)
        self.columnViewCH.setObjectName(_fromUtf8("columnViewCH"))
        self.tabWidget.addTab(self.tabCH, _fromUtf8(""))
        self.tabFX = QtGui.QWidget()
        self.tabFX.setObjectName(_fromUtf8("tabFX"))
        self.columnViewFX = QtGui.QColumnView(self.tabFX)
        self.columnViewFX.setGeometry(QtCore.QRect(16, 10, 560, 490))
        self.columnViewFX.setAlternatingRowColors(False)
        self.columnViewFX.setResizeGripsVisible(True)
        self.columnViewFX.setObjectName(_fromUtf8("columnViewFX"))
        self.tabWidget.addTab(self.tabFX, _fromUtf8(""))
        self.tabHelp = QtGui.QWidget()
        self.tabHelp.setObjectName(_fromUtf8("tabHelp"))
        self.frameHelp = QtGui.QFrame(self.tabHelp)
        self.frameHelp.setGeometry(QtCore.QRect(16, 10, 560, 490))
        self.frameHelp.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHelp.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameHelp.setObjectName(_fromUtf8("frameHelp"))
        self.label = QtGui.QLabel(self.frameHelp)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 490))
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tabHelp, _fromUtf8(""))
        self.pushBtnNew = QtGui.QPushButton(self.centralWidget)
        self.pushBtnNew.setGeometry(QtCore.QRect(10, 50, 140, 30))
        self.pushBtnNew.setObjectName(_fromUtf8("pushBtnNew"))
        self.checkBoxDebug = QtGui.QCheckBox(self.centralWidget)
        self.checkBoxDebug.setEnabled(True)
        self.checkBoxDebug.setGeometry(QtCore.QRect(10, 100, 140, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxDebug.sizePolicy().hasHeightForWidth())
        self.checkBoxDebug.setSizePolicy(sizePolicy)
        self.checkBoxDebug.setObjectName(_fromUtf8("checkBoxDebug"))
        self.labelProject = QtGui.QLabel(self.centralWidget)
        self.labelProject.setGeometry(QtCore.QRect(10, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelProject.setFont(font)
        self.labelProject.setObjectName(_fromUtf8("labelProject"))
        self.comboBox = QtGui.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 10, 80, 20))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.labelCredits = QtGui.QLabel(self.centralWidget)
        self.labelCredits.setGeometry(QtCore.QRect(10, 510, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelCredits.setFont(font)
        self.labelCredits.setTextFormat(QtCore.Qt.AutoText)
        self.labelCredits.setObjectName(_fromUtf8("labelCredits"))
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 140, 141, 361))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAlwaysOnTop = QtGui.QAction(MainWindow)
        self.actionAlwaysOnTop.setCheckable(True)
        self.actionAlwaysOnTop.setObjectName(_fromUtf8("actionAlwaysOnTop"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionAlwaysOnTop)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Assets Browser", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBG), _translate("MainWindow", "BG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCH), _translate("MainWindow", "CH", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFX), _translate("MainWindow", "FX", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Assets Browser v0.1.0<br/>Last updated: 30 July 2017</p><p>Placeholder text. Need to figure out a way to read in external HTML file to keep the Python script lean for easier coding/debugging.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("MainWindow", "Help", None))
        self.pushBtnNew.setText(_translate("MainWindow", "Create New Asset", None))
        self.checkBoxDebug.setText(_translate("MainWindow", "Show Debug Panel", None))
        self.labelProject.setText(_translate("MainWindow", "Project:", None))
        self.labelCredits.setText(_translate("MainWindow", "<html><head/><body><p>Huey Yeng © 2017<br/>http://taukeke.com</p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuView.setTitle(_translate("MainWindow", "&View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "&About Assets Browser", None))
        self.actionAlwaysOnTop.setText(_translate("MainWindow", "Always on &Top", None))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences...", None))

